### ISSUE TITLE
grafana docker image breaks when using proxys

### ISSUE THREAD

**Issue by jcpvdm** [srl-labs/sros-anysec-macsec-lab#24]
My machine needs to pass through a proxy to reach internet, so I passed proxy env vars to grafana node so it can download the plugins set in GF_INSTALL_PLUGINS:
```
no_proxy=localhost,172.50.50.0/24
https_proxy=http://proxy.local:8080/
HTTPS_PROXY=http://proxy.local:8080/
HTTP_PROXY=http://proxy.local:8080/
http_proxy=http://proxy.local:8080/
```

However, grafana is not ignoring the proxy when trying to reach internal node prometheus, therefore breaking the scenario. As workaround, instead of passing proxies to grafana, created a container with nginx hosting the plugin files.
```
 httprepo:
      kind: linux
      image: nginx
      mgmt-ipv4: 172.50.50.20
      binds:
        - ./httprepo/:/usr/share/nginx/html:ro
      group: "10"

grafana:
(...)
        GF_INSTALL_PLUGINS: http://httprepo/agenty-flowcharting-panel-1.0.0d.220606199-SNAPSHOT.zip;agenty-flowcharting-panel,http://httprepo/cloudspout-button-panel.zip;cloudspout-button-panel
```
